### ISSUE TITLE
HAX integration

### ISSUE THREAD

**Issue by michael-collins** [open-curriculum/oerschema#45]
**Tasks**

- [ ] OER Schema Alignment with schema.org and LRMI
- [ ] HAX Plugin development
  - [ ] Design: Pre-configured and configurable elements
